# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='viewerproduct',
            table='v_test',
        ),
    ]
