# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_auto_20170413_0454'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='viewerproduct',
            table=None,
        ),
    ]
